BancoArmarinho/BancoArmarinho/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Repositorio.Models;
using BancoArmarinho.Mapper;
using BancoArmarinho.Models;
using Microsoft.AspNetCore.Http;


namespace BancoArmarinho.Controllers
{
    public class CategoriaController : Controller
    {
        public IActionResult Index()
        {
            switch (new UsuarioRepositorio().VerificarPermissao(HttpContext.Session.GetInt32("Codigo"), 2))
            {
                case -1: return RedirectToAction("Login", "Usuario");
                case 0: return RedirectToAction("SemPermissao", "Usuario");
            }
            List<Categoria> lista = (new CategoriaRepositorio()).Consultar();

            var mapper = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());

            List<CategoriaModel> listaModel = mapper.Map<List<CategoriaModel>>(lista);

            return View(listaModel);
        }
        
        [HttpGet]
        public IActionResult Adiciona(int? id)
        {
            switch (new UsuarioRepositorio().VerificarPermissao(HttpContext.Session.GetInt32("Codigo"), 2))
            {
                case -1: return RedirectToAction("Login", "Usuario");
                case 0: return RedirectToAction("SemPermissao", "Usuario");
            }

            CategoriaModel model = new CategoriaModel();
            model.Codigo = 0;

            if (id.HasValue)
            {
                var mapper = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());
                model = mapper.Map<CategoriaModel>((new CategoriaRepositorio()).Consultar(id.Value));
            }

            return View(model);
        }
        
        [HttpPost]
        public IActionResult Adiciona(CategoriaModel model)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    var mapper = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());
                    Categoria cat = mapper.Map<Categoria>(model);

                    if (cat.Codigo == 0)
                    {
                        if ((new CategoriaRepositorio()).Inserir(cat))
                        {

                            ViewData["Menssagem"] = "SALVO !!";
                            model = new CategoriaModel();
                            model.Codigo = 0;
                            ModelState.Clear();
                        }
                        else
                        {
                            ViewData["Menssagem"] = "Categoria Já existe !!";
                        }
                    }
                    else
                    {
                        (new CategoriaRepositorio()).Alterar(cat);
                    }


                }
            }
            catch (Exception)
            {

                throw;
            }
            
            return View(model);
        }
        public JsonResult Buscar(String Prefix)
        {
            var map = new AutoMapper.Mapper(BancoArmarinho.Mapper.AutoMapperConfig.RegisterMappings());
            List<CategoriaModel> lista = map.Map<List<CategoriaModel>>((new CategoriaRepositorio()).Buscar(Prefix));
            return new JsonResult(lista);
        }


        public IActionResult Excluir(int id)
        {
            try
            {
                Categoria cat = (new CategoriaRepositorio()).Consultar(id);

                if (cat != null)
                {
                    new CategoriaRepositorio().Excluir(cat);
                    ViewData["Menssagem"] = "Excluido com sucesso !!";
                }
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("Index");
        }
    }
}

BancoArmarinho/BancoArmarinho/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Repositorio.Models;
using BancoArmarinho.Mapper;
using BancoArmarinho.Models;
using Microsoft.AspNetCore.Http;

namespace BancoArmarinho.Controllers
{
    public class ClienteController : Controller
    {
        public IActionResult Index()
        {
            switch (new UsuarioRepositorio().VerificarPermissao(HttpContext.Session.GetInt32("Codigo"), 2))
            {
                case -1: return RedirectToAction("Login", "Usuario");
                case 0: return RedirectToAction("SemPermissao", "Usuario");
            }
            List<Cliente> lista = new ClienteRepositorio().Consultar();

            var mapper = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());

            List<ClienteModel> listaModel = mapper.Map<List<ClienteModel>>(lista);

            return View(listaModel);
        }

        [HttpGet]
        public IActionResult Adiciona(int? id)
        {
            switch (new UsuarioRepositorio().VerificarPermissao(HttpContext.Session.GetInt32("Codigo"), 2))
            {
                case -1: return RedirectToAction("Login", "Usuario");
                case 0: return RedirectToAction("SemPermissao", "Usuario");
            }

            ClienteModel model = new ClienteModel();
            model.Codigo = 0;
           
            if (id.HasValue)
            {
                var mapper = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());
                model = mapper.Map<ClienteModel>((new ClienteRepositorio()).Consultar(id.Value));
            }

            return View(model);
        }
        public IActionResult Visualiza(int? id)
        {
            switch (new UsuarioRepositorio().VerificarPermissao(HttpContext.Session.GetInt32("Codigo"), 2))
            {
                case -1: return RedirectToAction("Login", "Usuario");
                case 0: return RedirectToAction("SemPermissao", "Usuario");
            }

            ClienteModel model = new ClienteModel();
            model.Codigo = 0;

            if (id.HasValue)
            {
                var mapper = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());
                model = mapper.Map<ClienteModel>((new ClienteRepositorio()).Consultar(id.Value));
            }

            return View(model);
        }
        [HttpPost]
        public IActionResult Adiciona(ClienteModel model)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    var mapper = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());
                    Cliente cat = mapper.Map<Cliente>(model);

                    cat.Pontos = 0;
                    cat.Situacao = true;
                    if (cat.Codigo == 0)
                    {
                        
                        if ((new ClienteRepositorio()).Inserir(cat))
                        {
                            ViewData["Menssagem"] = "SALVO !!";
                            model = new ClienteModel();
                            model.Codigo = 0;
                            ModelState.Clear();
                        }
                        else
                        {
                            ViewData["Menssagem"] = "Já existe !!";
                        }
                    }
                    else
                    {
                        (new ClienteRepositorio()).Alterar(cat);
                    }

                    //return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {

                throw;
            }
            return View(model);
        }

        public IActionResult Excluir(int id)
        {
            try
            {
                Cliente cat = (new ClienteRepositorio()).Consultar(id);

                if (cat != null)
                {
                    new ClienteRepositorio().Excluir(cat);
                    ViewData["Menssagem"] = "Excluido com sucesso !!";
                }
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("Index");
        }
        public IActionResult Ativadesativa(int id)
        {
            try
            {
                Cliente cat = (new ClienteRepositorio()).Consultar(id);

                if (cat != null)
                {
                    if(cat.Situacao == true)
                    {
                        cat.Situacao = false;
                    }
                    else
                    {
                        cat.Situacao = true;
                    }
                    new ClienteRepositorio().Alterar(cat);
                    ViewData["Menssagem"] = ": Alterado com sucesso !!";
                }
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("Index");
        }
        public JsonResult Buscar(String Prefix)
        {
            var map = new AutoMapper.Mapper(BancoArmarinho.Mapper.AutoMapperConfig.RegisterMappings());
            List<ClienteModel> lista = map.Map<List<ClienteModel>>((new ClienteRepositorio()).Buscar(Prefix));
            return new JsonResult(lista);
        }

    }
}

BancoArmarinho/BancoArmarinho/Controllers/CompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Repositorio.Models;
using BancoArmarinho.Mapper;
using BancoArmarinho.Models;
using Microsoft.AspNetCore.Http;

namespace BancoArmarinho.Controllers
{
        public class CompraController : Controller
        {
        

        public IActionResult Index()
            {
                switch (new UsuarioRepositorio().VerificarPermissao(HttpContext.Session.GetInt32("Codigo"), 3))
                {
                    case -1: return RedirectToAction("Login", "Usuario");
                    case 0: return RedirectToAction("SemPermissao", "Usuario");
                }
            List<Compra> lista = (new CompraRepositorio()).Consultar();

                var mapper = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());

            List<CompraModel> listaNota = mapper.Map<List<CompraModel>>(lista);

                return View(listaNota);
            }
        public IActionResult Index2()
        {
            switch (new UsuarioRepositorio().VerificarPermissao(HttpContext.Session.GetInt32("Codigo"), 3))
            {
                case -1: return RedirectToAction("Login", "Usuario");
                case 0: return RedirectToAction("SemPermissao", "Usuario");
            }
            List<Compra> lista = (new CompraRepositorio()).ConsultarEstorno();

            var mapper = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());

            List<CompraModel> listaNota = mapper.Map<List<CompraModel>>(lista);

            return View(listaNota);
        }

        public IActionResult Cadastrar()
            {
                switch (new UsuarioRepositorio().VerificarPermissao(HttpContext.Session.GetInt32("Codigo"), 3))
                {
                    case -1: return RedirectToAction("Login", "Usuario");
                    case 0: return RedirectToAction("SemPermissao", "Usuario");
                }
            return View();
            }

            public JsonResult finalizar(int codigo)
            {
                try
                {
                    Compra n = (new CompraRepositorio().Consultar(codigo));
                n.Stat = "F";
                //Altera estoque
                    List<Compraitens> ci = new CompraitensRepositorio().buscarProdutos(n.Codigo);
                    Produto p = new Produto();

                    foreach (var item in ci)
                    {
                        p = new ProdutoRepositorio().Consultar(item.Prodcod.Value);
                        p.Quantidade = p.Quantidade + item.Cquant;
                        p.Estoque2 = p.Estoque2 + item.Cquant;
                    new ProdutoRepositorio().Alterar(p);
                    }

                //altera compra
                new CompraRepositorio().Alterar(n);

                    return new JsonResult(true);
                }
                catch (Exception)
                {
                    return new JsonResult(false);
                }
            }

            [HttpPost]
            public JsonResult salvar([FromBody]CompraModel model)
            {
                try
                {
                    var map = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());

                    Compra n = map.Map<Compra>(model);

                    n.Data = DateTime.Now;

                    n.Stat = "I";

                    new CompraRepositorio().Inserir(n);

                    model.Codigo = n.Codigo;

                    return new JsonResult(model);
                }
                catch (Exception e)
                {
                    return new JsonResult(e);
                }
            }
        }
    }

BancoArmarinho/BancoArmarinho/Controllers/VendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Repositorio.Models;
using BancoArmarinho.Mapper;
using BancoArmarinho.Models;
using Microsoft.AspNetCore.Http;


namespace BancoArmarinho.Controllers
{
    public class VendaController : Controller
    {

        public IActionResult Index()
        {
            switch (new UsuarioRepositorio().VerificarPermissao(HttpContext.Session.GetInt32("Codigo"), 3))
            {
                case -1: return RedirectToAction("Login", "Usuario");
                case 0: return RedirectToAction("SemPermissao", "Usuario");
            }
            List<Venda> lista = (new VendaRepositorio()).Consultar();

            var mapper = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());

            List<VendaModel> listaModel = mapper.Map<List<VendaModel>>(lista);

            return View(listaModel);
        }


        public IActionResult create()
        {
            switch (new UsuarioRepositorio().VerificarPermissao(HttpContext.Session.GetInt32("Codigo"), 2))
            {
                case -1: return RedirectToAction("Login", "Usuario");
                case 0: return RedirectToAction("SemPermissao", "Usuario");
            }
            return View();
        }

        public JsonResult finalizar(int codigo)
        {
            try
            {
                Venda ven = (new VendaRepositorio().Consultar(codigo));
                ven.Valor = new ItensvendidosRepositorio().calcularTotal(codigo);

                //pontuação
                Cliente c = new ClienteRepositorio().Consultar(new VendaRepositorio().Consultar(ven.Codigo).Cliente.Value);
                
                c.Pontos += (int)(ven.Valor / 10);

                ven = (new VendaRepositorio().AtualizarVenda(ven, c));

                new ClienteRepositorio().Alterar(c);

                //desconto
                if (c.Pontos > 50)
                {
                    ven.Desconto = (ven.Valor / 100) * 5;
                }
                else
                {
                    ven.Desconto = 0;
                }
                //alterar quantidade estoque
                ven.Total = ven.Valor - ven.Desconto;
                //ven.Total = ven.Valor;
                List<Itensvendidos> ci = new ItensvendidosRepositorio().buscarProdutos(ven.Codigo);
                Produto p = new Produto();

                foreach(var item in ci)
                {
                    p = new ProdutoRepositorio().Consultar(item.Produto.Value);
                    p.Quantidade = p.Quantidade - item.Quantidade;
                    p.Estoque2 = p.Estoque2 - item.Quantidade;

                    new ProdutoRepositorio().Alterar(p);
                }
                //altera vendaa
                new VendaRepositorio().Alterar(ven);




                return new JsonResult(true);
            }
            catch (Exception)
            {
                return new JsonResult(false);
            }
        }

        [HttpPost]
        public JsonResult salvar([FromBody]VendaModel model)
        {
            try
            {
                var map = new AutoMapper.Mapper(BancoArmarinho.Mapper.AutoMapperConfig.RegisterMappings());

                Venda ven = map.Map<Venda>(model);

                ven.Data = DateTime.Now;

                new VendaRepositorio().Inserir(ven);

                model.Codigo = ven.Codigo;
               
                return new JsonResult(model);
            }
            catch (Exception)
            {
                return new JsonResult(null);
            }
        }
    }

}

BancoArmarinho/BancoArmarinho/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>@ViewData["Title"] - Promóveis</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <style>
        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            text-align: center;
        }
    </style>
</head>
<body style="background-color:#F1F2F1 ;"> 
    <nav class="navbar navbar-expand-lg navbar-light rounded-0 navbar-fixed-top" style="background-color:#D9D9D6;">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Promóveis</a>
            </div>
            <div class="navbar-collapse collapse">
                <nav class="navbar-nav mr-auto">
                    @* Relatórios *@
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Relatórios
                        </a>
                        <div class="dropdown-menu">
                            <a asp-area="" class="nav-link" asp-controller="Fornecedor" asp-action="Index">Fornecedor</a>
                            <a asp-area="" class="nav-link" asp-controller="Cliente" asp-action="Index">Cliente</a>
                            <a asp-area="" class="nav-link" asp-controller="Categoria" asp-action="Index">Categoria</a>
                            <a asp-area="" class="nav-link" asp-controller="Produto" asp-action="Index">Produto</a>
                            <a asp-area="" class="nav-link" asp-controller="Usuario" asp-action="Index">Usuario</a>
                            <a asp-area="" class="nav-link" asp-controller="Compra" asp-action="index">Compras</a>
                            <a asp-area="" class="nav-link" asp-controller="Compra" asp-action="index2">Estornos</a>
                            <a asp-area="" class="nav-link" asp-controller="Venda" asp-action="index">Venda</a>

                        </div>
                    </div>
                    <div class="dropdown-divider"></div>
                    @*Cadastro*@
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Cadastro
                        </a>
                        <div class="dropdown-menu">
                            <a asp-area="" class="nav-link" asp-controller="Fornecedor" asp-action="Adiciona">Fornecedor</a>
                            <a asp-area="" class="nav-link" asp-controller="Cliente" asp-action="Adiciona">Cliente</a>
                            <a asp-area="" class="nav-link" asp-controller="Categoria" asp-action="ADiciona">Categoria</a>
                            <a asp-area="" class="nav-link" asp-controller="Produto" asp-action="Adiciona">Produto</a>
                            <a asp-area="" class="nav-link" asp-controller="Usuario" asp-action="Adiciona">Usuario</a>


                        </div>
                    </div>
                    <div class="dropdown-divider"></div>
                    @*Conta Pagar*@
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Pagar e Receber
                        </a>
                        <div class="dropdown-menu">
                         <a asp-area="" class="nav-link" asp-controller="ContaPagar" asp-action="Adiciona">Adicionar a Pagar</a>
                         <a asp-area="" class="nav-link" asp-controller="ContaPagar" asp-action="index">Relatorio Contas a Pagar</a>
                         <a asp-area="" class="nav-link" asp-controller="Venda" asp-action="index">Relatorio de Contas a Receber</a>

                    </div>
                    </div>
                    @*Movimentação*@
                    <div class="dropdown-divider"></div>
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Movimentação
                        </a>
                        <div class="dropdown-menu">
                            <a asp-area="" class="nav-link" asp-controller="Venda" asp-action="Create">Venda</a>
                            <a asp-area="" class="nav-link" asp-controller="Compra" asp-action="Cadastrar">Compra</a>
                            <a asp-area="" class="nav-link" asp-controller="Compra" asp-action="Cadastrar">Estorno</a>
                        </div>
                    </div>


                </nav>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <a class="nav-link"><span class="glyphicon glyphicon-user"></span>  @Context.Request.HttpContext.Session.GetString("Usuario") </a> &ensp;
                <a  asp-area="" class="nav-link" asp-controller="Usuario" asp-action="Logout"><span class="glyphicon glyphicon-log-in"></span> Sair</a>
            </ul>
        </div>
        
        @*<div class="nav navbar-nav" align="right">
            <ul>
                <li> <a class="nav-link" asp-controller="Usuario" asp-action="Logout"> @Context.Request.HttpContext.Session.GetString("Usuario") | Sair </a></li>
            </ul>
        </div>*@
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr /> 
        <footer class="footer">
            <p>&copy; Promóveis Móveis Para Escritório LTDA-ME</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>