BancoArmarinho/BancoArmarinho/Controllers/FornecedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Repositorio.Models;
using BancoArmarinho.Mapper;
using BancoArmarinho.Models;
using Microsoft.AspNetCore.Http;

namespace BancoArmarinho.Controllers
{
    public class FornecedorController : Controller
    {

        public IActionResult Index()
        {
            switch (new UsuarioRepositorio().VerificarPermissao(HttpContext.Session.GetInt32("Codigo"), 3))
            {
                case -1: return RedirectToAction("Login", "Usuario");
                case 0: return RedirectToAction("SemPermissao", "Usuario");
            }
            List<Fornecedor> lista = new FornecedorRepositorio().Consultar();

            var mapper = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());

            List<FornecedorModel> listaModel = mapper.Map<List<FornecedorModel>>(lista);

            return View(listaModel);
        }

        [HttpGet]
        public IActionResult Adiciona(int? id)
        {
            switch (new UsuarioRepositorio().VerificarPermissao(HttpContext.Session.GetInt32("Codigo"), 3))
            {
                case -1: return RedirectToAction("Login", "Usuario");
                case 0: return RedirectToAction("SemPermissao", "Usuario");
            }
            FornecedorModel model = new FornecedorModel();
            model.Codigo = 0;

            if (id.HasValue)
            {
                var mapper = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());
                model = mapper.Map<FornecedorModel>((new FornecedorRepositorio()).Consultar(id.Value));
            }

            return View(model);
        }
        public IActionResult Visualiza(int? id)
        {
            switch (new UsuarioRepositorio().VerificarPermissao(HttpContext.Session.GetInt32("Codigo"), 3))
            {
                case -1: return RedirectToAction("Login", "Usuario");
                case 0: return RedirectToAction("SemPermissao", "Usuario");
            }
            FornecedorModel model = new FornecedorModel();
            model.Codigo = 0;

            if (id.HasValue)
            {
                var mapper = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());
                model = mapper.Map<FornecedorModel>((new FornecedorRepositorio()).Consultar(id.Value));
            }

            return View(model);
        }
        [HttpPost]
        public IActionResult Adiciona(FornecedorModel model)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    var mapper = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());
                    Fornecedor cat = mapper.Map<Fornecedor>(model);
                    cat.Situacao = true;
                    if (cat.Codigo == 0)
                    {
                        if ((new FornecedorRepositorio()).Inserir(cat))
                        {
                            ViewData["Menssagem"] = "SALVO !!";
                            model = new FornecedorModel();
                            model.Codigo = 0;
                            ModelState.Clear();
                        }
                        else
                        {
                            ViewData["Menssagem"] = "Fornecedor já existe !!";
                        }
                    }
                    else
                    {
                        (new FornecedorRepositorio()).Alterar(cat);
                    }

                    //return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {

                throw;
            }
            return View(model);
        }
        public JsonResult Buscar(string prefix)
        {
            var map = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());
            List<FornecedorModel> lista = map.Map<List<FornecedorModel>>(new FornecedorRepositorio().Consultar(prefix));
            return new JsonResult(lista);
        }
        public JsonResult Buscar2(string prefix)
        {
            var map = new AutoMapper.Mapper(AutoMapperConfig.RegisterMappings());
            List<FornecedorModel> lista = map.Map<List<FornecedorModel>>(new FornecedorRepositorio().Buscar(prefix));
            return new JsonResult(lista);
        }
        public IActionResult Excluir(int id)
        {
            try
            {
                Fornecedor cat = (new FornecedorRepositorio()).Consultar(id);

                if (cat != null)
                {
                    new FornecedorRepositorio().Excluir(cat);
                    ViewData["Menssagem"] = "Excluido com sucesso !!";
                }
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("Index");
        }

        public IActionResult Ativadesativa(int id)
        {
            try
            {
                Fornecedor cat = (new FornecedorRepositorio()).Consultar(id);

                if (cat != null)
                {
                    if (cat.Situacao == true)
                    {
                        cat.Situacao = false;
                    }
                    else
                    {
                        cat.Situacao = true;
                    }
                    new FornecedorRepositorio().Alterar(cat);
                    ViewData["Menssagem"] = ": Alterado com sucesso !!";
                }
            }
            catch (Exception)
            {

                throw;
            }

            return RedirectToAction("Index");
        }


    }
}

BancoArmarinho/BancoArmarinho/Views/Fornecedor/Adiciona.cshtml
@model BancoArmarinho.Models.FornecedorModel /* tipagem, definindo com o tipo do cadastro */
@{
    ViewData["Title"] = "Cadastro Fornecedor";
}

<div class="container-fluid">

    <h3 class="alert-success">@ViewData["Menssagem"]</h3>
    <h3>Cadastro Fornecedor </h3>
    <form asp-controller="Fornecedor" asp-action="Adiciona" method="post">

        <div class="form-group">
            <input type="hidden" asp-for="Codigo" class="form-control" />
        </div>

        <div class="form-group ">
            <div class="form-group row">
                <div class="col-md-6">
                    <label asp-for="Nome"></label>
                    <input type="text" asp-for="Nome" maxlength="50" class="form-control" required="required" />
                    <span asp-validation-for="Nome" class="alert-danger"></span>
                </div>
                <div class="col-md-6">
                    <label asp-for="Cnpj"></label>
                    <input id="txtDocumento" type="text" asp-for="Cnpj" class="form-control" required="required" />
                    <span asp-validation-for="Cnpj" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-2">
                    <label asp-for="Cep"></label>
                    <input id="txtCEP" type="text" asp-for="Cep" class="form-control" required="required" />
                    <span asp-validation-for="Cep" class="alert-danger"></span>

                </div>
                <div class="col-md-9">
                    <label asp-for="Endereço"></label>
                    <input id="txtEndereço" type="text" maxlength="50" asp-for="Endereço" class="form-control" required="required" />
                    <span asp-validation-for="Endereço" class="alert-danger"></span>
                </div>
                <div class="col-md-1">
                    <label asp-for="Numero"></label>
                    <input id="txtNumero" type="text" maxlength="5" onkeypress="return event.charCode >=48 && event.charCode <=57" asp-for="Numero" class="form-control" />
                    <span asp-validation-for="Numero" class="alert-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-5">
                    <label asp-for="Cidade"></label>
                    <input id="txtCidade" type="text" asp-for="Cidade" maxlength="50" class="form-control" required="required" />
                    <span asp-validation-for="Cidade" class="alert-danger"></span>
                </div>
                <div class="col-md-1">
                    <label asp-for="Estado"></label>
                    <input id="txtEstado" type="text" readonly asp-for="Estado" maxlength="2" class="form-control" required="required" />
                    <span asp-validation-for="Estado" class="alert-danger"></span>
                </div>
                <div class="col-md-3">
                    <label asp-for="Telefone"></label>
                    <input id="txtTelefone" type="text" asp-for="Telefone" class="form-control" required="required" />
                    <span asp-validation-for="Telefone" class="alert-danger"></span>
                </div>
                <div class="col-md-3">
                    <label asp-for="Telefone2"></label>
                    <input id="txtTelefone2" type="text" asp-for="Telefone2" class="form-control" />
                    <span asp-validation-for="Telefone2" class="alert-danger"></span>
                </div>
            </div>

        </div>

        <div class="form-group">

            @Html.ActionLink("Voltar", "Index", "Fornecedor", new { }, new { @class = "btn btn-secondary" })
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>

    </form>
</div>

@section Scripts    {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="http://digitalbush.com/wpcontent/uploads/2014/10/jquery.maskedinput.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.0/jquery.mask.js"></script>

    <script>

    $(function () {

        $("#txtDocumento").mask('00.000.000/0000-00', { reverse: false });
        $("#txtCEP").mask('00000-000', { reverse: false });
        $("#txtTelefone").mask('(00)000000009', { reverse: false });
        $("#txtTelefone2").mask('(00)000000009', { reverse: false });

    });
    </script>
}

BancoArmarinho/BancoArmarinho/Views/Fornecedor/Visualiza.cshtml
@model BancoArmarinho.Models.FornecedorModel /* tipagem, definindo com o tipo do cadastro */
@{
    ViewData["Title"] = "Fornecedor";
}
<h3 class="alert">@ViewData["Menssagem"]</h3>

<div class="container-fluid">

    <h3>Fornecedor</h3>
    <form asp-controller="Fornecedor" asp-action="Visualiza" >

        <div class="form-group">
            <input type="hidden" asp-for="Codigo" class="form-control" />
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="Nome"></label>
                    <input type="text" readonly asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="alert-danger"></span>
                </div>
                <div class="col-md-6">
                    <label asp-for="Cnpj"></label>
                    <input id="txtDocumento"  readonly type="text" asp-for="Cnpj" class="form-control" />
                    <span asp-validation-for="Cnpj" class="alert-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <label asp-for="Cep"></label>
                    <input id="txtCEP"  readonly type="text" asp-for="Cep" class="form-control" />
                    <span asp-validation-for="Cep" class="alert-danger"></span>

                </div>
                <div class="col-md-9">
                    <label asp-for="Endereço"></label>
                    <input id="txtEndereço"  readonly type="text" asp-for="Endereço" class="form-control" />
                    <span asp-validation-for="Endereço" class="alert-danger"></span>
                </div>
                <div class="col-md-1">
                    <label asp-for="Numero"></label>
                    <input id="txtNumero"  readonly type="text" maxlength="5" onkeypress="return event.charCode >=48 && event.charCode <=57" asp-for="Numero" class="form-control" />
                    <span asp-validation-for="Numero" class="alert-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <label asp-for="Cidade"></label>
                    <input id="txtCidade"  readonly type="text" asp-for="Cidade" class="form-control" />
                    <span asp-validation-for="Cidade" class="alert-danger"></span>
                </div>
                <div class="col-md-1">
                    <label asp-for="Estado"></label>
                    <input id="txtEstado"  readonly type="text" asp-for="Estado" class="form-control" />
                    <span asp-validation-for="Estado" class="alert-danger"></span>
                </div>
                <div class="col-md-3">
                    <label asp-for="Telefone"></label>
                    <input id="txtTelefone"  readonly type="text" asp-for="Telefone" class="form-control" />
                    <span asp-validation-for="Telefone" class="alert-danger"></span>
                </div>
                <div class="col-md-3">
                    <label asp-for="Telefone2"></label>
                    <input id="txtTelefone"  readonly type="text" asp-for="Telefone2" class="form-control" />
                    <span asp-validation-for="Telefone2" class="alert-danger"></span>
                </div>
            </div>

        </div>

        <div class="form-group">

            @Html.ActionLink("Voltar", "Index", "Fornecedor", new { }, new { @class = "btn btn-secondary" })
        </div>

    </form>
</div>

@section Scripts    {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="http://digitalbush.com/wpcontent/uploads/2014/10/jquery.maskedinput.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.0/jquery.mask.js"></script>

    <script>

    $(function () {

        $("#txtDocumento").mask('00.000.000/0000-00', { reverse: false });
        $("#txtCEP").mask('00000-000', { reverse: false });
        $("#txtTelefone").mask('(00)000000009', { reverse: false });
        $("#txtTelefone2").mask('(00)000000009', { reverse: false });

    });
    </script>
}

BancoArmarinho/BancoArmarinho/Views/Fornecedor/index.cshtml
@model IEnumerable<BancoArmarinho.Models.FornecedorModel> /* passagem de parametro pra a view, passei a lista de categorias */
@{
    ViewData["Title"] = "Relatório de Fornecedores";
}
<h3 class="alert-success">@ViewData["Mensagem"]</h3>
<br />
<h3>Relatório de Fornecedores: </h3>
<br />
<div style="overflow-y: scroll; height:400px; ">
    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(i => i.Nome)</th>
                <th>@Html.DisplayNameFor(i => i.Cnpj)</th>
                <th>@Html.DisplayNameFor(i => i.Cidade)</th>
                <th>@Html.DisplayNameFor(i => i.Estado)</th>
                <th>@Html.DisplayNameFor(i => i.Situacao)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (FornecedorModel item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(itemModel => item.Nome)</td>
                    <td>@Html.DisplayFor(itemModel => item.Cnpj)</td>
                    <td>@Html.DisplayFor(itemModel => item.Cidade)</td>
                    <td>@Html.DisplayFor(itemModel => item.Estado)</td>
                    @if (item.Situacao == true)
                    {
                        <td>
                            @Html.ActionLink("Ativo", "Ativadesativa", "Fornecedor", new { id = item.Codigo }, new { @class = "btn btn-success btn-block" })
                        </td>
                    }
                    else
                    {
                        <td>
                            @Html.ActionLink("Inativo", "Ativadesativa", "Fornecedor", new { id = item.Codigo }, new { @class = "btn btn btn-danger btn-block" })
                        </td>
                    }
                    <td>
                        @Html.ActionLink("Visualizar", "Visualiza", "Fornecedor", new { id = item.Codigo }, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Alterar", "Adiciona", "Fornecedor", new { id = item.Codigo }, new { @class = "btn btn-warning" })
                        @*@Html.ActionLink("Excluir", "Excluir", "Fornecedor", new { id = item.Codigo }, new { @class = "btn btn-danger", onclick = "return confirm ('Deseja Excluir?')" })*@
                    </td>
                </tr>
            }
        </tbody>
    </table>
    </div>